import type {Metadata} from "next";

import React from "react";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* apply noise.png to background */}
      <body
        className="bg-cover bg-center"
        style={{
          backgroundImage: "url('/noise.png')",
        }}
      >
        {children}
      </body>
    </html>
  );
}
